name: Terraform with Policy as Code

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1
      TF_STATE_BUCKET: my-terraform-state-bucket-12345678901234     # S3 bucket name
      TF_STATE_KEY: terraform.tfstate
      TF_STATE_DYNAMODB_TABLE: my-terraform-lock     # DynamoDB table for locking

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.0

      - name: Terraform Init with S3 Backend
        run: |
          terraform init -backend-config="bucket=$TF_STATE_BUCKET" \
                         -backend-config="key=$TF_STATE_KEY" \
                         -backend-config="region=$AWS_REGION" \
                         -backend-config="dynamodb_table=$TF_STATE_DYNAMODB_TABLE"

      - name: Terraform Plan
        run: |
          terraform plan -out="myplan.tfplan"
          echo "Terraform plan created: myplan.tfplan"

      - name: Export Plan to JSON
        run: |
          if [ ! -s myplan.tfplan ]; then
              echo "No Terraform plan generated. Creating empty JSON."
              echo "{}" > myplan.json
          else
              terraform show -json myplan.tfplan > myplan.json
              echo "myplan.json created from Terraform plan."
          fi

      - name: Validate JSON & Check Resource Changes
        run: |
          if ! jq empty myplan.json >/dev/null 2>&1; then
              echo "Error: myplan.json is not valid JSON!"
              head -10 myplan.json
              exit 1
          fi

          if [ "$(jq '.resource_changes | length // 0' myplan.json)" -eq 0 ]; then
              echo "No resource changes detected. Skipping OPA and apply."
              exit 0
          fi

          echo "myplan.json is valid and has resource changes."

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.37.0/conftest_0.37.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.37.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/
          conftest --version

      - name: Run OPA Policies
        run: conftest test myplan.json --policy ./opa-policies/

      - name: Terraform Apply (manual approval required)
        if: success()
        run: |
          echo "Terraform apply will run only after manual approval."
          echo "Please approve this step in GitHub Actions to continue."
