name: Terraform with Policy as Code

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.0  # Use a version that supports -json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (binary)
        run: |
          terraform plan -out="myplan.tfplan"
          echo "Terraform plan completed."

      - name: Export Plan to JSON
        run: |
          if [ -s tfplan ]; then
              terraform show -json myplan.tfplan > myplan.json
              echo "myplan.json created."
          else
              echo "{}" > myplan.json
              echo "No changes detected, created empty JSON."
          fi

      - name: Validate myplan.json
        run: |
          if ! jq empty myplan.json >/dev/null 2>&1; then
              echo "Error: myplan.json is not valid JSON!"
              head -10 myplan.json
              exit 1
          fi

          if [ "$(jq '.resource_changes | length // 0' myplan.json)" -eq 0 ]; then
              echo "Terraform plan has no resource changes. Skipping OPA and apply."
              exit 0
          fi

          echo "myplan.json is valid and has resource changes."

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.37.0/conftest_0.37.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.37.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/
          conftest --version

      - name: Run OPA Policies
        run: conftest test myplan.json --policy ./opa-policies/


      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve myplan.tfplan
